[[ch-hm-module]]
== Home Manager

:nvim-metals: https://github.com/scalameta/nvim-metals
:nix-config: https://github.com/gvolpe/nix-config
:searchable-options: https://gvolpe.com/neovim-flake/search.html
:ts-grammars: https://github.com/gvolpe/neovim-flake/blob/main/lib/buildPlugin.nix#L15

The Home Manager module allows us to customize the different `vim` options. To use it, we first add the input flake.

[source,nix]
----
{
  neovim-flake = {
    url = github:gvolpe/neovim-flake;
    inputs.nixpkgs.follows = "nixpkgs";
  };
}
----

Followed by importing the HM module.

[source,nix]
----
{
  imports = [ neovim-flake.nixosModules.hm ];
}
----

Then we should be able to use the given module. E.g.

[source,nix]
----
{
  programs.neovim-ide = {
    enable = true;
    settings = {
      vim.viAlias = false;
      vim.vimAlias = true;
      vim.lsp = {
        enable = true;
      };
    };
  };
}
----

Besides the classic <<ch-options>>, you can also use the {searchable-options}[searchable module options].

For the Scala module, the `metals` binary can be easily overridden with the provided builder. E.g.

[source,nix]
----
{
  vim.lsp = {
    enable = true;
    scala = {
      enable = true;
      metals = pkgs.metalsBuilder {
        version = "0.11.8+76-22425a8b-SNAPSHOT";
        outputHash = "[Insert hash (try nix build .#)]";
      };
    };
  };
}
----

It enables the featureful and recommended {nvim-metals}[nvim-metals].

[NOTE]
====
To use `metalsBuilder`, you need to add the following overlay.
====

[source,nix]
----
{
  pkgs = import nixpkgs {
    inherit system;
    overlays = [ neovim-flake.overlays.default ];
  };
}
----

You can have a look at my {nix-config}[nix-config] for a full example.

=== Packages

Besides the full-fledged IDE and HM modules, there are a few packages exposed that may prove useful to your use case.

- `ts-scala`: tree-sitter-scala version that tracks the latest master changes.
- `nvim-treesitter`: latest nvim-treesitter ensuring compatibility with `tree-sitter-scala`.

If you have your own NeoVim configuration, you can still leverage `nvim-treesitter` by first adding the overlay, and then using the following package.

[source,nix]
----
{
  programs.neovim = {
    enable = true;
    plugins = [
      pkgs.neovimPlugins.nvim-treesitter
    ];
  };
}
----

Or more directly without the overlay.

[source,nix]
----
{
  programs.neovim = {
    enable = true;
    plugins = [
      inputs.neovim-flake.packages.${system}.nvim-treesitter
    ];
  };
}
----

You can see all the enabled grammars for this package {ts-grammars}[here].

The `ts-scala` package only builds `tree-sitter-scala` from `master`, but it wouldn't be as useful for your own configuration because `nvim-treesitter` requires a few tweaks.

=== Configuration files

Furthermore, the generated `neovimRC` and `luaRC` files for every flavor of Neovim exposed by this flake are also available as derivations for better visibility.

- `ide-lua-rc`
- `ide-neovim-rc`
- `haskell-lua-rc`
- `haskell-neovim-rc`
- `scala-lua-rc`
- `scala-neovim-rc`

These could also be useful to debug when plugins don't work as expected.
